<?php
use Codilar\FormDataInsertToAdminGrid\Block\SaveUrl;
/**
 * @var $block SaveUrl
 */
?>

<form action="<?= $block->getPostUrl() ?>" method="POST">
    <fieldset>

        <div>
            <label for="name"><?= __("Name :") ?></label>
            <input type="text" name="name"/>
        </div>

        <div>
            <label for="email"><?= __("Email : ") ?></label>
            <input type="email" name="email"/>
        </div>

        <div>
            <label for="address"><?= __("Address : ") ?></label>
            <input type="text" name="address"/>
        </div>

        <div>
            <label for="image"><?= __("Image :") ?></label>
            <input type="file" name="image"/>
        </div>
        <input type="submit" name="submit" value="<?= __("Submit Data ") ?>" />

    </fieldset>

</form>
